import React, { useState } from 'react';
import {
  Sparkles,
  FileText,
  CheckCircle2,
  ListChecks,
  Lightbulb,
  Compass,
  Copy,
  Check,
  Download,
  RotateCcw,
  BookOpen,
  Layers,
  Clock,
  HardDrive
} from 'lucide-react';
import { formatBytes, countWords, estimateReadingTime } from '../utils/fileUtils';

export default function SummaryResults({
  result,
  fileMeta,
  selectedLength,
  onReset
}) {
  const [copied, setCopied] = useState(false);

  const { summary, keyPoints = [], mainIdeas = [], suggestions = [] } = result || {};
  const wordCount = countWords(summary);
  const readTime = estimateReadingTime(summary);

  const handleCopy = async () => {
    const fullText = `=== DOCUMIND AI SUMMARY ===
Document: ${fileMeta?.name || 'Uploaded Document'}
Summary Depth: ${selectedLength.toUpperCase()}

--- DOCUMENT SUMMARY ---
${summary}

--- KEY POINTS ---
${keyPoints.map((p, i) => `${i + 1}. ${p}`).join('\n')}

--- MAIN IDEAS ---
${mainIdeas.map((m, i) => `${i + 1}. ${m}`).join('\n')}

--- IMPROVEMENT SUGGESTIONS ---
${suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}
`;

    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback
    }
  };

  const handleDownload = () => {
    const markdownContent = `# DocuMind AI Document Analysis

**File Name:** ${fileMeta?.name || 'Document'}  
**File Type:** ${fileMeta?.isPdf ? 'PDF Document' : 'Image Document'}  
**File Size:** ${formatBytes(fileMeta?.size)}  
${fileMeta?.pageCount ? `**Page Count:** ${fileMeta.pageCount}  \n` : ''}**Analysis Depth:** ${selectedLength.toUpperCase()}  
**Generated At:** ${new Date().toLocaleString()}  

---

## 📄 Document Summary
${summary}

---

## 🎯 Key Points
${keyPoints.map((pt) => `- ${pt}`).join('\n')}

---

## 💡 Main Ideas
${mainIdeas.map((idea) => `- ${idea}`).join('\n')}

---

## 🚀 Improvement Suggestions
${suggestions.map((sug) => `- ${sug}`).join('\n')}

---
*Generated by DocuMind – AI Document Summary Assistant*
`;

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${(fileMeta?.name || 'DocuMind_Summary').replace(/\.[^/.]+$/, '')}_summary.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="results-container">
      {/* Top Banner */}
      <div className="results-hero-card">
        <div className="hero-top-row">
          <div className="hero-badge-group">
            <span className="success-badge">
              <CheckCircle2 size={15} /> AI ANALYSIS COMPLETE
            </span>
            <span className="length-badge">
              <Sparkles size={13} /> {selectedLength.toUpperCase()} DEPTH
            </span>
          </div>

          <div className="hero-action-buttons">
            <button
              type="button"
              className="action-btn copy-btn"
              onClick={handleCopy}
              title="Copy full analysis to clipboard"
            >
              {copied ? (
                <>
                  <Check size={15} className="text-success" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy size={15} />
                  <span>Copy Analysis</span>
                </>
              )}
            </button>

            <button
              type="button"
              className="action-btn download-btn"
              onClick={handleDownload}
              title="Export analysis as Markdown file"
            >
              <Download size={15} />
              <span>Export MD</span>
            </button>

            <button
              type="button"
              className="action-btn reset-btn"
              onClick={onReset}
              title="Analyze another document"
            >
              <RotateCcw size={15} />
              <span>Analyze Another</span>
            </button>
          </div>
        </div>

        {/* Document Info Strip */}
        <div className="doc-meta-strip">
          <div className="meta-item">
            <FileText size={15} className="meta-icon" />
            <div className="meta-text">
              <span className="meta-label">File Name</span>
              <span className="meta-value" title={fileMeta?.name}>
                {fileMeta?.name || 'Document'}
              </span>
            </div>
          </div>

          <div className="meta-item">
            <HardDrive size={15} className="meta-icon" />
            <div className="meta-text">
              <span className="meta-label">Format & Size</span>
              <span className="meta-value">
                {fileMeta?.isPdf ? 'PDF' : 'Image'} • {formatBytes(fileMeta?.size)}
              </span>
            </div>
          </div>

          {fileMeta?.pageCount && (
            <div className="meta-item">
              <Layers size={15} className="meta-icon" />
              <div className="meta-text">
                <span className="meta-label">Pages</span>
                <span className="meta-value">{fileMeta.pageCount} page{fileMeta.pageCount > 1 ? 's' : ''}</span>
              </div>
            </div>
          )}

          <div className="meta-item">
            <Clock size={15} className="meta-icon" />
            <div className="meta-text">
              <span className="meta-label">Est. Summary Read</span>
              <span className="meta-value">{readTime} min ({wordCount} words)</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Results Grid */}
      <div className="results-grid">
        {/* 1. DOCUMENT SUMMARY */}
        <section className="result-card summary-card" aria-labelledby="summary-title">
          <div className="card-header">
            <div className="card-title-group">
              <div className="card-icon-pill icon-blue">
                <BookOpen size={18} />
              </div>
              <div>
                <h3 id="summary-title" className="card-title">DOCUMENT SUMMARY</h3>
                <p className="card-subtitle">Synthesized executive overview generated from extracted content</p>
              </div>
            </div>
          </div>
          <div className="card-body">
            <p className="summary-paragraph">{summary}</p>
          </div>
        </section>

        {/* 2. KEY POINTS */}
        <section className="result-card keypoints-card" aria-labelledby="keypoints-title">
          <div className="card-header">
            <div className="card-title-group">
              <div className="card-icon-pill icon-indigo">
                <ListChecks size={18} />
              </div>
              <div>
                <h3 id="keypoints-title" className="card-title">KEY POINTS</h3>
                <p className="card-subtitle">Critical facts, statistics, and essential findings</p>
              </div>
            </div>
          </div>
          <div className="card-body">
            <ul className="points-list">
              {keyPoints.map((point, index) => (
                <li key={index} className="point-item">
                  <div className="point-bullet-box">
                    <span className="point-number">{index + 1}</span>
                  </div>
                  <span className="point-text">{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 3. MAIN IDEAS */}
        <section className="result-card mainideas-card" aria-labelledby="mainideas-title">
          <div className="card-header">
            <div className="card-title-group">
              <div className="card-icon-pill icon-violet">
                <Compass size={18} />
              </div>
              <div>
                <h3 id="mainideas-title" className="card-title">MAIN IDEAS</h3>
                <p className="card-subtitle">Core overarching themes and strategic takeaways</p>
              </div>
            </div>
          </div>
          <div className="card-body">
            <ul className="points-list">
              {mainIdeas.map((idea, index) => (
                <li key={index} className="point-item">
                  <div className="point-bullet-box idea-box">
                    <span className="point-number">{index + 1}</span>
                  </div>
                  <span className="point-text">{idea}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 4. IMPROVEMENT SUGGESTIONS */}
        <section className="result-card suggestions-card" aria-labelledby="suggestions-title">
          <div className="card-header">
            <div className="card-title-group">
              <div className="card-icon-pill icon-amber">
                <Lightbulb size={18} />
              </div>
              <div>
                <h3 id="suggestions-title" className="card-title">IMPROVEMENT SUGGESTIONS</h3>
                <p className="card-subtitle">Actionable recommendations and constructive next steps</p>
              </div>
            </div>
          </div>
          <div className="card-body">
            <div className="suggestions-grid">
              {suggestions.map((suggestion, index) => (
                <div key={index} className="suggestion-item">
                  <div className="suggestion-badge-icon">
                    <Lightbulb size={16} />
                  </div>
                  <div className="suggestion-content">
                    <span className="suggestion-title">Recommendation {index + 1}</span>
                    <p className="suggestion-text">{suggestion}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>

      {/* Bottom Sticky Bar for easy reset */}
      <div className="bottom-reset-bar">
        <button
          type="button"
          className="btn-primary-reset"
          onClick={onReset}
        >
          <RotateCcw size={18} />
          <span>Analyze Another Document</span>
        </button>
      </div>
    </div>
  );
}
